name: coveralls
on: [push, pull_request]

jobs:
  coveralls:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - uses: actions/checkout@v1
      - name: npm install
        run: |
          npm install
          npm run test -- --coverage
      - name: Run Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: run-$ {{matrix.test_number}}
          parallel: true

    finish:
        needs: coveralls
        runs-on: ubuntu-latest
        steps:
        - name: Coveralls Finished
          uses: coverallsapp/github-action@master
          with:
            github-token: ${{ secrets.github_token }}
            parallel-finished: true
