name: coveralls
on: [pull_request]

jobs:
  coveralls:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - uses: actions/checkout@v1
      - name: npm install
        run: |
          cd ui
          npm install
      - name: Run Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ui/coverage/lcov.info